config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  namespace :admin do

    root to: 'homes#top'

    resources :customers, only: [:index, :show, :edit, :update]

    resources :items, only: [:index, :show, :edit, :new, :create, :update]

    resources :orders, only: [:show, :update]

    resources :order_details, only: [:update]

    resources :genres, only: [:index, :edit, :create, :update]


  end


  scope module: :public do

    devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

     root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"



    get 'customers/information' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'

    patch 'unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    get 'unsubscribe_check' => 'customers#unsubscribe_check'

    resources :items, only: [:index, :show]

    resources :carts, only: [:index, :update, :destroy, :create]
      delete 'destroy_all' => 'carts#destroy_all'

    resources :orders, only:[:index, :new, :show, :create]
    post 'confirm' => 'orders#confirm'
    get 'thx' => 'orders#thx'

    resources :deliveries, only: [:index, :edit, :create, :update, :destroy]

  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.with_tax_price * quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code , presence: true
  validates :address , presence: true
  validates :phone_number , presence: true
  validates :email , presence: true

 has_many :carts, dependent: :destroy
 has_many :deliveries, dependent: :destroy


  def full_name
    self.last_name + ' ' + self.first_name
  end

  def full_name_kana
    self.last_name_kana + ' ' + self.first_name_kana
  end

  def full_address
    '〒' + post_code + ' ' + address + ' ' + full_name
  end

end

app/models/delivery.rb
class Delivery < ApplicationRecord
belongs_to :customer

validates :post_code , presence: true
validates :address , presence: true
validates :name , presence: true

  def address_all
    '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true, uniqueness: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :carts
  has_many :order_details
  belongs_to :genre

  validates :image, presence: true
  validates :name, presence: true
  validates :infomation, presence: true

  def with_tax_price
      (price_no_tax * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details

    validates :post_code ,presence: true
    validates :address ,presence: true
    validates :name ,presence: true

    enum payment_method: { credit_card: 0, transfer: 1 }
    enum select_address: { my_address: 0, address_index: 1, address_new: 2}
    enum order_status: { payment_waiting: 0, payment_finish: 1, production: 2, ready_delivery: 3, delivery_finish: 4 }
    
    def with_tax_price
      (price_no_tax * 1.1).floor
    end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  
  enum production_status: { "not_available": 0, "production_waiting": 1, "in_production": 2, "production_finish": 3,}

    belongs_to :order
    belongs_to :item
    
    def subtotal_order
        tax_in_price * quantity
    end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:address,:post_code,:phone_number,:is_deleted)
  end

  def update

  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path(@genre)
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @itempage = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      @item.errors.full_messages.each  do| msg |
        pp msg
      end

      @genres = Genre.all
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item)
    else
    @genres = Genre.all
    render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id,:name,:infomation,:image,:price_no_tax,:is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/deliveries_controller.rb
class Public::DeliveriesController < ApplicationController

  def index
    @delivery = Delivery.new
    @deliveries = Delivery.all
  end

  def create
    @delivery = Delivery.new(delivery_params)
    @delivery.customer_id = current_customer.id
    @delivery.save
    redirect_to action: :index
  end

  def edit
    @delivery = Delivery.find(params[:id])
  end

  def update
    @delivery = Delivery.find(params[:id])
    @delivery.update(delivery_params)
    redirect_to deliveries_path
  end

  def destroy

  end

  private

  def delivery_params
    params.require(:delivery).permit(:post_code, :address, :name)
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
   <h3><%= @customer.full_name %>さんの会員情報編集</h3>
   </div>
   <div class="row">
    <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
    <table class="table table-borderless">
      <tr>
      <th>会員ID</th>
      <th><%= @customer.id %></th>
      </tr>

      <tr>
      <th><%= f.label :氏名 %></th>
      <th><%= f.text_field :last_name %></th>
      <th><%= f.text_field :first_name %></th>
      </tr>

      <tr>
      <th><%= f.label :カナ %></th>
      <th><%= f.text_field :last_name_kana %></th>
      <th><%= f.text_field :first_name_kana %></th>
      </tr>

      <tr>
      <th><%= f.label :郵便番号 %></th>
      <th><%= f.text_field :post_code %></th>
      </tr>

      <tr>
      <th><%= f.label :住所 %></th>
      <th><%= f.text_field :address %></th>
      <tr>

      <tr>
      <th><%= f.label :電話番号 %></th>
      <th><%= f.text_field :phone_number %></th>
      </tr>

      <tr>
      <th><%= f.label :メールアドレス %></th>
      <th><%= f.text_field :email %></th>
      </tr>

      <tr>
      <th>会員ステータス</th>
      <th>
      <%= f.radio_button :is_deleted, true %>
      <%= f.label :退会 %>
      </th>
      <th>
      <%= f.radio_button :is_deleted, false %>
      <%= f.label :有効 %>
      </th>
      </tr>
    </table>
    <p class="text-center">
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    </p>
      <% end %>
   </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col m-3">
      <h3>会員一覧</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <th><%= customer.id %></th>
            <th><%= link_to customer.full_name, admin_customer_path(customer) %></th>
            <th><%= customer.email %></th>
            <% if customer.is_deleted? == true %>
            <th class="text-denger text-center">退会</th>
            <% else %>
            <th class="text-success text-center">有効</th>
            <% end %>
          </tr>
          <% end %>
          <th><%= paginate @customers %></th>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col md-3">
      <h3 class="taxt-white"><%= @customer.full_name %>さんの会員詳細</h3>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>会員ID</th>
            <th><%= @customer.id %></th>
          </tr>
          <tr>
            <th>氏名</th>
            <th><%= @customer.full_name %></th>
          </tr>
          <tr>
            <th>フリガナ</th>
            <th><%= @customer.full_name_kana %></th>
          </tr>
          <tr>
            <th>郵便番号</th>
            <th>〒<%= @customer.post_code%></th>
          </tr>
          <tr>
            <th>住所</th>
            <th><%= @customer.address %></th>
          </tr>
          <tr>
            <th>電話番号</th>
            <th><%= @customer.phone_number %></th>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <th><%= @customer.email %></th>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <% if @customer.is_deleted? == true %>
            <th class="text-danger">退会</th>
            <% else %>
            <th class="text-success">有効</th>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="text-center">
        <%= link_to "編集する",edit_admin_customer_path, class: "btn btn-success" %>
        <%= link_to "注文履歴一覧を見る",admin_customers_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>