config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  namespace :admin do

    root to: 'homes#top'

    resources :customers, only: [:index, :show, :edit, :update]

    resources :items, only: [:index, :show, :edit, :new, :create, :update]

    resources :orders, only: [:show, :update]

    resources :order_details, only: [:update]

    resources :genres, only: [:index, :edit, :create, :update]


  end


  scope module: :public do

    devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

     root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"



    get 'customers/information' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'

    patch 'unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    get 'unsubscribe_check' => 'customers#unsubscribe_check'

    resources :items, only: [:index, :show]

    resources :carts, only: [:index, :update, :destroy, :create]
      delete 'destroy_all' => 'carts#destroy_all'

    resources :orders, only:[:index, :new, :show, :create]
    post 'confirm' => 'orders#confirm'
    get 'thx' => 'orders#thx'

    resources :deliveries, only: [:index, :edit, :create, :update, :destroy]

  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.with_tax_price * quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code , presence: true
  validates :address , presence: true
  validates :phone_number , presence: true
  validates :email , presence: true

 has_many :carts, dependent: :destroy
 has_many :deliveries, dependent: :destroy


  def full_name
    self.last_name + ' ' + self.first_name
  end

  def full_name_kana
    self.last_name_kana + ' ' + self.first_name_kana
  end

  def full_address
    '〒' + post_code + ' ' + address + ' ' + full_name
  end

end

app/models/delivery.rb
class Delivery < ApplicationRecord
belongs_to :customer

validates :post_code , presence: true
validates :address , presence: true
validates :name , presence: true

  def address_all
    '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true, uniqueness: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :carts
  has_many :order_details
  belongs_to :genre

  validates :image, presence: true
  validates :name, presence: true
  validates :infomation, presence: true

  def with_tax_price
      (price_no_tax * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details

    validates :post_code ,presence: true
    validates :address ,presence: true
    validates :name ,presence: true

    enum payment_method: { credit_card: 0, transfer: 1 }
    enum select_address: { my_address: 0, address_index: 1, address_new: 2}
    enum order_status: { payment_waiting: 0, payment_finish: 1, production: 2, ready_delivery: 3, delivery_finish: 4 }
    
    def with_tax_price
      (price_no_tax * 1.1).floor
    end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  
  enum production_status: { "not_available": 0, "production_waiting": 1, "in_production": 2, "production_finish": 3,}

    belongs_to :order
    belongs_to :item
    
    def subtotal_order
        tax_in_price * quantity
    end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path(@genre)
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @itempage = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      @item.errors.full_messages.each  do| msg |
        pp msg
      end

      @genres = Genre.all
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item)
    else
    @genres = Genre.all
    render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id,:name,:infomation,:image,:price_no_tax,:is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController


  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @sum = 0
    @postage = 800
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.order_status == "payment_finish"
      @order_details.update_all(production_status: "production_waiting")
    end
      redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/deliveries_controller.rb
class Public::DeliveriesController < ApplicationController

  def index
    @delivery = Delivery.new
    @deliveries = Delivery.all
  end

  def create
    @delivery = Delivery.new(delivery_params)
    @delivery.customer_id = current_customer.id
    @delivery.save
    redirect_to action: :index
  end

  def edit
    @delivery = Delivery.find(params[:id])
  end

  def update
    @delivery = Delivery.find(params[:id])
    @delivery.update(delivery_params)
    redirect_to deliveries_path
  end

  def destroy

  end

  private

  def delivery_params
    params.require(:delivery).permit(:post_code, :address, :name)
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col m-3">
      <h2>ジャンル編集</h2>
        <%= form_with model: @genre, url: admin_genre_path(@genre),method: :patch do |f| %>
          ジャンル名
          <%= f.text_field :name %>
      <p class="text-center">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<dev class="container">
  <div class="row">
    <div class="col m-3">
      <h3>ジャンル一覧・追加</h3>
      <div class="my-8">
        <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <tr>
          <td>ジャンル名</td>
          <td><%= f.text_field :name %></td>
          <td><%= f.submit "新規登録", class: "btn btn-success" %></td>
        </tr>
        <% end %>
      </div>
      <table class="table table-borderless">
        <thead>
          <tr>
            <td>ジャンル</td>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</dev>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col m-3">
      <h3>注文履歴一覧</h3>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>注文日時</th>
            <th>注文者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <tr>
          <% @orders.each do |order| %>
            <th>
              <%= link_to admin_order_path(order) do %>
              <%= order.created_at.strftime("%Y/%m/%d") %>
              <% end %>
            </th>
            <th><%= order.customer.full_name %></th>
            <th><%= order.order_details.sum(:quantity) %></th>
            <th><%= order.order_status %></th>
          </tr>
          <% end %>
          <th><%= paginate @orders %></th>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="row">
  <div class="col m-3">
    <h2>商品編集</h2>
    <div class="mx-auto">
      <%= form_with model: @item, url: admin_item_path(@item) do |f| %>
      <table class="table table-borderless">
        <tr>
          <th><%= f.label :商品画像 %></th>
          <th><%= f.file_field :image,accept: "image/*" %></th>
        </tr>
        <tr>
          <th><%= f.label :商品名 %></th>
          <th><%= f.text_field :name %></th>
        </tr>
        <tr>
          <th><%= f.label :商品説明 %></th>
          <th><%= f.text_area :infomation %></th>
        </tr>
        <tr>
          <th><%= f.label :ジャンル %></th>
          <th><%= f.collection_select(:genre_id,@genres, :id, :name, {prompt: "選択"}) %></th>
        </tr>
        <tr>
          <th><%= f.label :税抜価格 %></th>
          <th><%= f.text_field :price_no_tax %>円</th>
        </tr>
        <tr>
          <th><%= f.label :販売ステータス%></th>
          <th>
          <%= f.radio_button :is_active, true %>
          <%= f.label :販売中 %>
          <%= f.radio_button :is_active, false %>
          <%= f.label :販売停止中 %>
          </th>
        </tr>
      </table>
      <p class="text-center">
      <%= f.submit "変更を保存", class: "btn btn-success" %>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col m-3">
      <h3>商品一覧</h3>
      <%= link_to new_admin_item_path do %>
      <i class="fa-regular fa-square-plus"></i>商品新規登録
      <% end %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @itempage.each do |item| %>
          <tr>
            <th><%= item.id %></th>
            <th><%= link_to item.name, admin_item_path(item) %></th>
            <th><%= item.price_no_tax %>円</th>
            <th><%= item.genre.name %></th>
            <th>
              <% if item.is_active? == true %>
              <span class="text-success">販売中</span>
              <% else %>
              <span class="text-danger">販売停止中</span>
              <% end %>
            </th>
          </tr>
          <% end %>
          <th><%= paginate @itempage %></th>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="row">
  <div class="col m-3">
    <h2>商品新規登録</h2>
    <div class="mx-auto">
      <%= form_with model: @item, url: admin_items_path do |f| %>
      <table class="table table-borderless">
        <tr>
          <th><%= f.label :商品画像 %></th>
          <th><%= f.file_field :image,accept: "image/*" %></th>
        </tr>
        <tr>
          <th><%= f.label :商品名 %></th>
          <th><%= f.text_field :name %></th>
        </tr>
        <tr>
          <th><%= f.label :商品説明 %></th>
          <th><%= f.text_area :infomation %></th>
        </tr>
        <tr>
          <th><%= f.label :ジャンル %></th>
          <th><%= f.collection_select(:genre_id,@genres, :id, :name, {prompt: "選択"}) %></th>
        </tr>
        <tr>
          <th><%= f.label :税抜価格 %></th>
          <th><%= f.text_field :price_no_tax %>円</th>
        </tr>
        <tr>
          <th><%= f.label :販売ステータス%></th>
          <th>
          <%= f.radio_button :is_active, true %>
          <%= f.label :販売中 %>
          <%= f.radio_button :is_active, false %>
          <%= f.label :販売停止中 %>
          </th>
        </tr>
      </table>
      <p class="text-center">
      <%= f.submit "新規登録", class: "btn btn-success" %>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col md-3">
      <h3>商品詳細</h3>
      <div class="col mt-5">
        <% if @item.image.attached? %>
        <%= image_tag @item.image, size: "200x200" %>
        <% else %>
        <%= image_tag 'no_image', size: "200x200" %>
        <% end %>
      </div>
      <div class="col -5">
        <table class="table table-borderless">
          <tr>
            <th>商品名</th>
            <th><%= @item.name %></th>
          </tr>
          <tr>
            <th>商品説明</th>
            <th><%= @item.infomation %></th>
          </tr>
          <tr>
            <th>ジャンル</th>
            <th><%= @item.genre.name%></th>
          </tr>
          <tr>
            <th>税込価格(税抜価格)</th>
            <th>
              <%= @item.with_tax_price %>円
              (<%= @item.price_no_tax %>)円
            </th>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <th>
              <% if @item.is_active? == true %>
              <span>販売中</span>
              <% else %>
              <span>販売停止中</span>
              <% end %>
            </th>
          </tr>
          <div class="text-center">
            <%= link_to "編集する", edit_admin_item_path(@item), class: 'btn btn-success' %>
          </div>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row mt-4 ml-4">
    <h3>注文履歴詳細</h3>
    <div class="row mt-2">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>購入者</th>
            <th>
              <%= @order.customer.full_name %>
            </th>
          </tr>
          <tr>
            <th>注文日</th>
            <th><%= @order.created_at.strftime("%Y/%m/%d") %></th>
          </tr>
          <tr>
            <th>配送先</th>
            <th><%= @order.post_code %></th>
          </tr>
          <tr>
            <th>支払方法</th>
            <th><%= @order.payment_method %></th>
          </tr>
          <tr>
            <th>注文ステータス</th>
            <th>
              <%= form_with model: @order, url: admin_order_path(@order),method: :patch do |f| %>
              <%= f.select :order_status,Order.order_statuses_i18n.values.to_a.zip(Order.order_statuses.keys.to_a) %>
              <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </th>
          </tr>
        </tbody>
      </table>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <th><%= order_detail.item.name %></th>
            <th><%= order_detail.tax_in_price %></th>
            <th><%= order_detail.quantity %></th>
            <th><%= order_detail.tax_in_price*order_detail.quantity %></th>
            <% @sum += order_detail.tax_in_price*order_detail.quantity %>
            <th>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail),method: :patch do |f| %>
              <%= f.select :production_status, OrderDetail.production_statuses_i18n.values.to_a.zip(OrderDetail.production_statuses_i18n.keys.to_a) %>
              <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="col d-flex">
        <table class="table table-borderless">
          <tr>
            <th>商品合計</th>
            <th><%= @sum %>円</th>
          </tr>
          <tr>
            <th>送料</th>
            <th><%= @postage %>円</th>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <th><%= @sum + @postage %>円</th>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>