config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  namespace :admin do

    root to: 'homes#top'

    resources :customers, only: [:index, :show, :edit, :update]

    resources :items, only: [:index, :show, :edit, :new, :create, :update]

    resources :orders, only: [:show, :update]

    resources :order_details, only: [:update]

    resources :genres, only: [:index, :edit, :create, :update]


  end


  scope module: :public do

    devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

     root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"



    get 'customers/information' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'

    patch 'unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    get 'unsubscribe_check' => 'customers#unsubscribe_check'

    resources :items, only: [:index, :show]

    resources :carts, only: [:index, :update, :destroy, :create]
      delete 'destroy_all' => 'carts#destroy_all'

    resources :orders, only:[:index, :new, :show, :create]
    post 'confirm' => 'orders#confirm'
    get 'thx' => 'orders#thx'

    resources :deliveries, only: [:index, :edit, :create, :update, :destroy]

  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.with_tax_price * quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code , presence: true
  validates :address , presence: true
  validates :phone_number , presence: true
  validates :email , presence: true

 has_many :carts, dependent: :destroy
 has_many :deliveries, dependent: :destroy


  def full_name
    self.last_name + ' ' + self.first_name
  end

  def full_name_kana
    self.last_name_kana + ' ' + self.first_name_kana
  end

  def full_address
    '〒' + post_code + ' ' + address + ' ' + full_name
  end

end

app/models/delivery.rb
class Delivery < ApplicationRecord
belongs_to :customer

validates :post_code , presence: true
validates :address , presence: true
validates :name , presence: true

  def address_all
    '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true, uniqueness: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :carts
  has_many :order_details
  belongs_to :genre

  validates :image, presence: true
  validates :name, presence: true
  validates :infomation, presence: true

  def with_tax_price
      (price_no_tax * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details

    validates :post_code ,presence: true
    validates :address ,presence: true
    validates :name ,presence: true

    enum payment_method: { credit_card: 0, transfer: 1 }
    enum select_address: { my_address: 0, address_index: 1, address_new: 2}
    enum order_status: { payment_waiting: 0, payment_finish: 1, production: 2, ready_delivery: 3, delivery_finish: 4 }
    
    def with_tax_price
      (price_no_tax * 1.1).floor
    end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  
  enum production_status: { "not_available": 0, "production_waiting": 1, "in_production": 2, "production_finish": 3,}

    belongs_to :order
    belongs_to :item
    
    def subtotal_order
        tax_in_price * quantity
    end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @itempage = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      @item.errors.full_messages.each  do| msg |
        pp msg
      end

      @genres = Genre.all
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item)
    else
    @genres = Genre.all
    render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id,:name,:infomation,:image,:price_no_tax,:is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/deliveries_controller.rb
class Public::DeliveriesController < ApplicationController

  def index
    @delivery = Delivery.new
    @deliveries = Delivery.all
  end

  def create
    @delivery = Delivery.new(delivery_params)
    @delivery.customer_id = current_customer.id
    @delivery.save
    redirect_to action: :index
  end

  def edit
    @delivery = Delivery.find(params[:id])
  end

  def update
    @delivery = Delivery.find(params[:id])
    @delivery.update(delivery_params)
    redirect_to deliveries_path
  end

  def destroy

  end

  private

  def delivery_params
    params.require(:delivery).permit(:post_code, :address, :name)
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_massage.html.erb
<% if instance.errors.any? %>
  <%= instance.errors.count %>件のエラーが発生しました
  <ul>
    <% instance.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <%= link_to root_path do %>
    <%= image_tag 'nagano_cake.jpg', :size => '200x100' %>
  <% end %>
  <nav class="my-2 my-md-0 md-3">
    <% if customer_signed_in? %>
    ようこそ<%= current_customer.full_name %>さん！
　　<%= link_to "マイページ", customers_information_path, class: "btn btn-outline-primary" %>
　　<%= link_to "商品一覧", items_path, class: "btn btn-outline-primary" %>
　　<%= link_to "カート", carts_path, class: "btn btn-outline-primary" %>
　　<%= link_to "ログアウト", destroy_customer_session_path,method: :delete, class: "btn btn-outline-primary" %>
　　<% elsif admin_signed_in? %>
　　<%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-primary" %>
　　<%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-primary" %>
　　<%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-primary" %>
　　<%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-primary" %>
　　<%= link_to "ログアウト", destroy_admin_session_path,method: :delete, class: "btn btn-outline-primary" %>
　　<% else %>
　　<%= link_to "About", about_path, class: "btn btn-outline-primary" %>
　　<%= link_to "商品一覧", items_path, class: "btn btn-outline-primary" %>
　　<%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-primary" %>
　　<% if current_page?(new_admin_session_path) %>
　　<%= link_to "ログイン", new_admin_session_path, class: "btn btn-outline-primary" %>
　　<% else %>
　　<%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-primary" %>
　　<% end %>

　　<% end %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="background-color: #cc9999;">

      <%= render 'layouts/header' %>

    </header>
    <%= yield %>
    <footer style="height: 50px; background-color: #cc9999;">
    </footer>

  </body>
</html>